// ExpressionEvaluation
// Expression Evaluation Using Stack
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac ExpressionEvaluation.java
// Run:
//   java ExpressionEvaluation
//
// Author: Generated by assistant

public class ExpressionEvaluation {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for ExpressionEvaluation - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
