// MergePointLinkedLists
// Find Merge Point of Two Linked Lists
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac MergePointLinkedLists.java
// Run:
//   java MergePointLinkedLists
//
// Author: Generated by assistant

public class MergePointLinkedLists {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for MergePointLinkedLists - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
