// MergeSortedLinkedLists
// Merge Two Sorted Linked Lists
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac MergeSortedLinkedLists.java
// Run:
//   java MergeSortedLinkedLists
//
// Author: Generated by assistant

public class MergeSortedLinkedLists {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for MergeSortedLinkedLists - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
