// ProductOfThreeLargest
// Product of Three Largest Distinct Elements
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac ProductOfThreeLargest.java
// Run:
//   java ProductOfThreeLargest
//
// Author: Generated by assistant

public class ProductOfThreeLargest {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for ProductOfThreeLargest - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
