// InfixToPostfix
// Infix to Postfix Conversion
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac InfixToPostfix.java
// Run:
//   java InfixToPostfix
//
// Author: Generated by assistant

public class InfixToPostfix {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for InfixToPostfix - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
