// MinStack
// MINSTACK Implementation
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac MinStack.java
// Run:
//   java MinStack
//
// Author: Generated by assistant

public class MinStack {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for MinStack - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
