// CircularQueue
// Circular Queue (k)
//
// Starter Java template. Implement methods as required by the practical.
//
// Compile:
//   javac CircularQueue.java
// Run:
//   java CircularQueue
//
// Author: Generated by assistant

public class CircularQueue {

    // Entry point for quick manual testing
    public static void main(String[] args) {
        System.out.println("Starter for CircularQueue - implement methods and tests here.");
    }

    // Add your methods below for the practical
}
